name: Docker Image CI Python
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
 
    - name: Log in to Docker Hub
      run: echo "${{ secrets.PASS }}" | docker login -u "${{ secrets.USER }}" --password-stdin
 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ankesh28/dockerwebserver
 
    - name: Push Docker Image
      run: docker push ankesh28/dockerwebserver
